Trac_WorkReport/Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Mvc;
using Trac_WorkReport.Models;
using WorkRport.DataAccess.Repository.IRepository;

namespace Trac_WorkReport.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly IProjectRepository _ProjectsRepo;

        public ProjectsController(IProjectRepository db)
        {
            _ProjectsRepo = db;
        }
        public IActionResult Index()
        {
            List<Projects> objprojects = _ProjectsRepo.GetAll().ToList();
            return View(objprojects);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Projects obj)
        {
            _ProjectsRepo.Add(obj);
            _ProjectsRepo.save();
            return RedirectToAction("Index");
        }


        public IActionResult Edit(Guid id)
        {
            if (id == null || id == null)
            {
                return NotFound();
            }
            Projects? projectsfromDb = _ProjectsRepo.Get(u => u.ProjectId == id);
            //Designation? designationfromDb1 = _db.Designations.FirstOrDefault(u=>u.DesId == id);
            //Designation? designationfromDb2 = _db.Designations.Where(u => u.DesId == id).FirstOrDefault();
            if (projectsfromDb == null)
            {
                return NotFound();
            }
            return View(projectsfromDb);
        }

        [HttpPost]
        public IActionResult Edit(Projects obj)
        {
            if (ModelState.IsValid)
            {
                _ProjectsRepo.update(obj);
                _ProjectsRepo.save();
                return RedirectToAction("Index");

            }
            return View();
        }



        public IActionResult Delete(Guid id)
        {
            if (id == null || id == null)
            {
                return NotFound();
            }
            Projects? projectsfromDb = _ProjectsRepo.Get(u => u.ProjectId == id);
            // Designation? designationfromDb1 = _db.Designations.FirstOrDefault(u => u.DesId == id);
            // Designation? designationfromDb2 = _db.Designations.Where(u => u.DesId == id).FirstOrDefault();
            if (projectsfromDb == null)
            {
                return NotFound();
            }
            return View(projectsfromDb);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(Guid id)
        {
            Projects? obj = _ProjectsRepo.Get(u => u.ProjectId == id); if (obj == null)
            {
                return NotFound();
            }
            _ProjectsRepo.Remove(obj);
            _ProjectsRepo.save();
            return RedirectToAction("Index");

            //return View();
        }
    }
}

Trac_WorkReport/Controllers/TSController.cs
//////using Microsoft.AspNetCore.Mvc;
//////using Microsoft.AspNetCore.Identity;
//////using WorkReport.Models;
//////using WorkRport.DataAccess.Repository.IRepository;
//////using System.Collections.Generic;
//////using System.Linq;
//////using System.Threading.Tasks;
//////using Trac_WorkReport.Models;
//////using WorkReport.Models.Models;

//////namespace Trac_WorkReport.Controllers
//////{
//////    public class TSController : Controller
//////    {
//////        private readonly UserManager<ApplicationUser> _userManager;
//////        private readonly RoleManager<ApplicationRole> _roleManager;
//////        private readonly IEmployeeMapRepository _employeeMapRep;

//////        public TSController(UserManager<ApplicationUser> userManager, RoleManager<ApplicationRole> roleManager, IEmployeeMapRepository employeeMapRep)
//////        {
//////            _userManager = userManager;
//////            _roleManager = roleManager;
//////            _employeeMapRep = employeeMapRep;
//////        }

//////        public async Task<IActionResult> Index()
//////        {
//////            var currentUser = await _userManager.GetUserAsync(User);
//////            if (currentUser == null)
//////            {
//////                return NotFound();
//////            }

//////            var currentUserRoles = await _userManager.GetRolesAsync(currentUser);
//////            var allUsers = _userManager.Users.ToList();
//////            var allUsersWithRoles = new List<EditUserViewModelTS>();
//////            var alluserswithRRR = new List<EditUserViewModelTS>();

//////            foreach (var user in allUsers)
//////            {
//////                var roles = await _userManager.GetRolesAsync(user);
//////                allUsersWithRoles.Add(new EditUserViewModelTS
//////                {
//////                    Id = user.Id,
//////                    Email = user.Email,
//////                    EmployeeID = user.EmployeeID,
//////                    EmployeeName = user.EmployeeName,
//////                    Roles = roles.Select(r => new RoleViewModelTS
//////                    {
//////                        RoleName = r,
//////                        IsSelected = true
//////                    }).ToList()

//////                });
//////            }

//////            // Fetch reporting officer names using EmployeeMapRepository
//////            //var reportingOfficerNames = _employeeMapRep.GetReportingOfficerName(currentUser.Id).ToList();

//////            // Fetch the reviewing officer name for the current user
//////            var reviewingOfficerName = _employeeMapRep.GetReviewingOfficerName(currentUser.Id);
//////            var reportingOfficerName = _employeeMapRep.GetReportingOfficerName(currentUser.Id);

//////            // Assign reporting officer names to corresponding users
//////            //for (int i = 0; i < allUsersWithRoles.Count; i++)
//////            //{
//////            //    allUsersWithRoles[i].ReportingOfficerName = reportingOfficerNames[i];
//////            //}

//////            var model = new UserIndexViewModelTS
//////            {
//////                CurrentUser = new EditUserViewModelTS
//////                {
//////                    Id = currentUser.Id,
//////                    Email = currentUser.Email,
//////                    EmployeeID = currentUser.EmployeeID,
//////                    EmployeeName = currentUser.EmployeeName,
//////                    ReviewingofficerName=reviewingOfficerName,
//////                    ReportingOfficerName = reportingOfficerName,

//////                    Roles = currentUserRoles.Select(r => new RoleViewModelTS
//////                    {
//////                        RoleName = r,
//////                        IsSelected = true
//////                    }).ToList()
//////                },
//////                AllUsersWithRoles = allUsersWithRoles
//////            };

//////            return View(model);
//////        }


//////        public async Task<IActionResult> Create(TimeSheet timeSheet)
//////        {
//////            var currentUser = await _userManager.GetUserAsync(User);
//////            if (currentUser == null)
//////            {
//////                return NotFound();
//////            }

//////            var currentUserRoles = await _userManager.GetRolesAsync(currentUser);
//////            var allUsers = _userManager.Users.ToList();
//////            var allUsersWithRoles = new List<EditUserViewModelTS>();
//////            var alluserswithRRR = new List<EditUserViewModelTS>();

//////            foreach (var user in allUsers)
//////            {
//////                var roles = await _userManager.GetRolesAsync(user);
//////                allUsersWithRoles.Add(new EditUserViewModelTS
//////                {
//////                    Id = user.Id,
//////                    Email = user.Email,
//////                    EmployeeID = user.EmployeeID,
//////                    EmployeeName = user.EmployeeName,
//////                    Roles = roles.Select(r => new RoleViewModelTS
//////                    {
//////                        RoleName = r,
//////                        IsSelected = true
//////                    }).ToList()

//////                });
//////            }

//////            // Fetch reporting officer names using EmployeeMapRepository
//////            //var reportingOfficerNames = _employeeMapRep.GetReportingOfficerName(currentUser.Id).ToList();

//////            // Fetch the reviewing officer name for the current user
//////            var reviewingOfficerName = _employeeMapRep.GetReviewingOfficerName(currentUser.Id);
//////            var reportingOfficerName = _employeeMapRep.GetReportingOfficerName(currentUser.Id);

//////            // Assign reporting officer names to corresponding users
//////            //for (int i = 0; i < allUsersWithRoles.Count; i++)
//////            //{
//////            //    allUsersWithRoles[i].ReportingOfficerName = reportingOfficerNames[i];
//////            //}

//////            var model = new UserIndexViewModelTS
//////            {
//////                CurrentUser = new EditUserViewModelTS
//////                {
//////                    Id = currentUser.Id,
//////                    Email = currentUser.Email,
//////                    EmployeeID = currentUser.EmployeeID,
//////                    EmployeeName = currentUser.EmployeeName,
//////                    ReviewingofficerName = reviewingOfficerName,
//////                    ReportingOfficerName = reportingOfficerName,

//////                    Roles = currentUserRoles.Select(r => new RoleViewModelTS
//////                    {
//////                        RoleName = r,
//////                        IsSelected = true
//////                    }).ToList()
//////                },
//////                AllUsersWithRoles = allUsersWithRoles
//////            };

//////            return View(model);
//////        }

//////        [HttpPost]
//////        public IActionResult Create(TimeSheet TimeS)
//////        {
//////            // _ProjectsRepo.Add(obj);
//////            // _ProjectsRepo.save();
//////            return RedirectToAction("Index");
//////        }
//////    }



//////    public class UserIndexViewModelTS
//////    {
//////        public EditUserViewModelTS CurrentUser { get; set; }
//////        public List<EditUserViewModelTS> AllUsersWithRoles { get; set; }
//////    }

//////    public class EditUserViewModelTS
//////    {
//////        public string Id { get; set; }
//////        public string Email { get; set; }
//////        public string EmployeeName { get; set; }
//////        public string EmployeeID { get; set; }
//////        public List<RoleViewModelTS> Roles { get; set; }
//////        public string ReportingOfficerName { get; set; }

//////        public string ReviewingofficerName { get; set; }
//////    }

//////    public class RoleViewModelTS
//////    {
//////        public string RoleName { get; set; }
//////        public bool IsSelected { get; set; }
//////    }
//////}

////using Microsoft.AspNetCore.Mvc;
////using Microsoft.AspNetCore.Identity;
////using WorkReport.Models;
////using WorkRport.DataAccess.Repository.IRepository;
////using System.Collections.Generic;
////using System.Linq;
////using System.Threading.Tasks;
////using Trac_WorkReport.Models;
////using WorkReport.Models.Models;

////namespace Trac_WorkReport.Controllers
////{
////    public class TSController : Controller
////    {
////        private readonly UserManager<ApplicationUser> _userManager;
////        private readonly RoleManager<ApplicationRole> _roleManager;
////        private readonly IEmployeeMapRepository _employeeMapRep;

////        public TSController(UserManager<ApplicationUser> userManager, RoleManager<ApplicationRole> roleManager, IEmployeeMapRepository employeeMapRep)
////        {
////            _userManager = userManager;
////            _roleManager = roleManager;
////            _employeeMapRep = employeeMapRep;
////        }

////        public async Task<IActionResult> Index()
////        {
////            var currentUser = await _userManager.GetUserAsync(User);
////            if (currentUser == null)
////            {
////                return NotFound();
////            }

////            var currentUserRoles = await _userManager.GetRolesAsync(currentUser);
////            var allUsers = _userManager.Users.ToList();
////            var allUsersWithRoles = new List<EditUserViewModelTS>();

////            foreach (var user in allUsers)
////            {
////                var roles = await _userManager.GetRolesAsync(user);
////                allUsersWithRoles.Add(new EditUserViewModelTS
////                {
////                    Id = user.Id,
////                    Email = user.Email,
////                    EmployeeID = user.EmployeeID,
////                    EmployeeName = user.EmployeeName,

Trac_WorkReport/Views/TS/AssignWork.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using WorkReport.Models.Models
@model UserIndexViewModelTS

@{
    // Convert UTC +5:30 to local time
    var localDate = DateTime.UtcNow.AddHours(5).AddMinutes(30).ToString("dd/MM/yyyy");
}

<form asp-action="AssignWork" method="post">
    <!-- User Information Section -->
    <div class="container mt-4">
        <div class="card shadow">
            <div class="card-body">
                <h5 class="card-title">User Information</h5>
                <hr>
                @* //<input id="" asp-for="@Model.CurrentUser.Id" hidden />*@
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="fullName">Full Name</label>
                            <input type="text" class="form-control" id="fullName" value="@Model.CurrentUser.EmployeeName" readonly>
                        </div>
                        <div class="form-group">
                            <label for="employeeID">Employee ID</label>
                            <input type="text" class="form-control" id="employeeID" value="@Model.CurrentUser.EmployeeID" readonly>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="reportingOfficer">Reporting Officer</label>
                            <input type="text" class="form-control" id="reportingOfficer" value="@Model.CurrentUser.ReportingOfficerName" readonly>
                        </div>
                        <div class="form-group">
                            <label for="designation">Reviewing Officer</label>
                            <input type="text" class="form-control" id="designation" value="@Model.CurrentUser.ReviewingofficerName" readonly>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Project Addition Form -->
    <div class="container mt-4">
        <div class="card shadow">
            <div class="card-body">
                <h5 class="card-title text-primary">Add Work</h5>
                <hr>
                <div class="form-group">
                    <label asp-for="TimeSheet.ReportDate">Date</label>
                    <div class="input-group">
                        <input type="text" class="form-control datepicker" asp-for="TimeSheet.ReportDate" placeholder="Select Date" readonly>
                        <span class="input-group-text bg-primary text-light"><i class="bi bi-calendar"></i></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="TimeSheet.Work">Work Title</label>
                    <textarea class="form-control" asp-for="TimeSheet.WorkTitle" rows="2" placeholder="Enter your Work Title"></textarea>
                </div>
                <div class="form-group">
                    <label asp-for="TimeSheet.Work">Work Details</label>
                    <textarea class="form-control" asp-for="TimeSheet.Work" rows="6" placeholder="Enter your Work Details"></textarea>
                </div>
                <div class="text-right mt-3">
                    <button type="submit" class="btn btn-primary btn-lg">Submit</button>
                    <a href="@Url.Action("Index", "TS")" class="btn btn-secondary btn-lg">Back To List</a>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <script>
        $(document).ready(function () {
            var today = new Date();
            // var formattedDate = (today.getMonth() + 1) + '/' + today.getDate() + '/' + today.getFullYear();
            // var formattedDate = '@localDate';

            //// Adjust the date and time to UTC+5:30 timezone
            //today.setHours(today.getHours() + 5); // Add 5 hours
            //today.setMinutes(today.getMinutes() + 30); // Add 30 minutes

            //var formattedDate = (today.getDate() < 10 ? '0' : '') + today.getDate() + '/' + ((today.getMonth() + 1) < 10 ? '0' : '') + (today.getMonth() + 1) + '/' + today.getFullYear() + ' ' + ((today.getHours() < 10 ? '0' : '') + today.getHours()) + ':' + ((today.getMinutes() < 10 ? '0' : '') + today.getMinutes());

            var formattedDate = (today.getDate() < 10 ? '0' : '') + today.getDate() + '/' + ((today.getMonth() + 1) < 10 ? '0' : '') + (today.getMonth() + 1) + '/' + today.getFullYear() + ' ' + ((today.getHours() < 10 ? '0' : '') + today.getHours()) + ':' + ((today.getMinutes() < 10 ? '0' : '') + today.getMinutes());

            $('.datepicker').datepicker({
                format: 'dd/mm/yyyy',
                todayHighlight: true,
                autoclose: true,
                endDate: today,
                orientation: 'auto'
            }).val(formattedDate);

            // Trigger datepicker only when the datepicker icon is clicked
            $('.input-group-text').on('click', function () {
                $('.datepicker').datepicker('show');
            });
        });
    </script>
}

Trac_WorkReport/Views/TS/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


@* For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860 *@
@{
}

@* For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860 *@
@{
}

@* For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860 *@
@{
}@*
@using WorkReport.Models.Models;
@model UserIndexViewModelTS

@{
    ViewData["Title"] = "User Index";
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card shadow-sm">
                <div class="card-header bg-primary text-white">
                    <h4 class="mb-0">User Details</h4>
                </div>
                <div class="card-body">
                    <div class="row mb-3">
                        <div class="col-sm-2">
                            <label class="col-form-label">Full Name</label>
                        </div>
                        <div class="col-sm-4">
                            <p class="form-control-plaintext text-primary fw-bold">@Model.CurrentUser.EmployeeName</p>
                        </div>
                        <div class="col-sm-2">
                            <label class="col-form-label">Employee ID</label>
                        </div>
                        <div class="col-sm-4">
                            <p class="form-control-plaintext text-secondary">@Model.CurrentUser.EmployeeID</p>
                        </div>
                    </div>
                    <hr>
                    <div class="row mb-3">
                        <div class="col-sm-2">
                            <label class="col-form-label">Reporting Officer</label>
                        </div>
                        <div class="col-sm-4">
                            @if (string.IsNullOrEmpty(Model.CurrentUser.ReportingOfficerName))
                            {
                                <p class="form-control-plaintext text-danger">No Reporting Officer Assigned</p>
                            }
                            else
                            {
                                <p class="form-control-plaintext text-success">@Model.CurrentUser.ReportingOfficerName</p>
                            }
                        </div>
                        <div class="col-sm-2">
                            <label class="col-form-label">Designation</label>
                        </div>
                        <div class="col-sm-4">
                            @foreach (var role in Model.CurrentUser.Roles)
                            {
                                <span class="badge bg-secondary me-1">@role.RoleName</span>
                            }
                        </div>
                    </div>
                    <hr>
                    <div class="row mb-3">
                        <div class="col-sm-2">
                            <label class="col-form-label">Reviewing Officer</label>
                        </div>
                        <div class="col-sm-4">
                            <p class="form-control-plaintext text-danger">@Model.CurrentUser.ReviewingofficerName</p>
                        </div>
                        <div class="col-sm-6 text-end">
                            <a asp-controller="TS" asp-action="Create" class="btn btn-primary">
                                <i class="bi bi-plus-circle"></i> Add Self Report
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<h4 class="mt-5">Employees List</h4>
<div class="row mt-4">
    <div class="col-md-12">
        <table class="table table-bordered table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>Employee Number</th>
                    <th>Employee Name</th>
                    <th>Role</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var emp in Model.employeeWithRoles.OrderBy(p => p.EmployeeName))
                {
                    <tr>
                        <td>@emp.employeeID</td>
                        <td>@emp.EmployeeName</td>
                        <td>@emp.RoleName</td>
                        <td class="text-center">
                            <div class="btn-group" role="group">
                                <a asp-controller="Projects" asp-action="Edit" asp-route-id="@emp.Id" class="btn btn-sm btn-primary">
                                    <i class="bi bi-pencil-square"></i> View Report
                                </a>
                                <a asp-controller="Projects" asp-action="Delete" asp-route-id="@emp.Id" class="btn btn-sm btn-danger">
                                    <i class="bi bi-plus-circle"></i> Assign Work
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
*@
@using WorkReport.Models.Models;
@model UserIndexViewModelTS

@{
    ViewData["Title"] = "User Index";

    string[] allowedRolesForEmployeeList = { "SO","ASO", "ADG", "LO", "AO", "HOD","JD" };
    string[] allowedRolesForSelfReport = { "SA", "ASO", "PA", "SO", "GIS Analyst" };

    string[] norepreviewofc = { "HOD", "LO", "JD", "AO" };

    string[] allowedRolesForWR = { "SA", "PA", "SRSA", "RSA", "GIS Analyst", "PE" };

    bool userHasAllowedRoleForEmployeeList = UserHasAnyRole(allowedRolesForEmployeeList);
    bool userHasAllowedRoleForSelfReport = UserHasAnyRole(allowedRolesForSelfReport);
    bool userHasallowedRolesForWR = UserHasAnyRole(allowedRolesForWR);
    bool usernorepreviewofc = UserHasAnyRole(norepreviewofc);
}

@functions {
    public bool UserHasAnyRole(string[] roles)
    {
        foreach (var role in roles)
        {
            if (User.IsInRole(role))
            {
                return true;
            }
        }
        return false;
    }
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card text-white border-primary shadow-sm">
                <div class="card-header">
                    <h4 class="mb-0">User Details</h4>
                </div>
                <div class="card-body">
                    <div class="row mb-4">
                        <div class="col-sm-6">
                            <div class="mb-3">
                                <label class="form-label col-form-label">Full Name:</label>
                                <p class="form-text  d-inline-block ms-3">@Model.CurrentUser.EmployeeName</p>
                            </div>
                            <div class="mb-3">
                                <label class="form-label fw-bold">Designation:</label>
                                <p class="form-text d-inline-block">
                                    @foreach (var role in Model.CurrentUser.Roles)
                                    {
                                        <span class="card-text me-1">@role.RoleName</span>
                                    }
                                </p>
                            </div>
                                @if (!usernorepreviewofc)
                            {
                                <div class="mb-3">
                                    <label class="form-label fw-bold">Reporting Officer:</label>
                                    <p class="form-text d-inline-block">
                                        @if (string.IsNullOrEmpty(Model.CurrentUser.ReportingOfficerName))
                                        {
                                            <span class="text-danger">No Reporting Officer Assigned</span>
                                        }
                                        else
                                        {
                                            @Model.CurrentUser.ReportingOfficerName
                                        }
                                    </p>
                                </div>
                            }
                        </div>
                        <div class="col-sm-6">
                            <div class="mb-3">
                                <label class="form-label fw-bold">Employee ID:</label>
                                <p class="form-text fw-bold d-inline-block ms-3 text-light">@Model.CurrentUser.EmployeeID</p>
                            </div>
                            @if (!usernorepreviewofc)
                    {
                            <div class="mb-3">
                                <label class="form-label fw-bold">Reviewing Officer:</label>
                                <p class="form-text text-danger d-inline-block">@Model.CurrentUser.ReviewingofficerName</p>
                            </div>
                    }
                        </div>
                    </div>
                </div>
                    @if (userHasAllowedRoleForSelfReport)
                    {
                        <div class="card-footer text-muted">
                        <div class="row">
                            <div class="col text-end">
                                <a asp-controller="TS" asp-action="ViewReport" asp-route-id="@Model.CurrentUser.Id" class="btn btn-primary">
                                    <i class="bi bi-pencil-square"></i> View Report
                                </a>
                                <a asp-controller="TS" asp-action="Create" class="btn btn-primary ms-2">
                                    <i class="bi bi-plus-circle"></i> Add Self Report
                                </a>
                            </div>
                        </div>
                        </div>
                    }
                </div>
          
        </div>
    </div>


</div>


<div class="container mt-5">
    <div class="row justify-content-center">


        @if (userHasAllowedRoleForEmployeeList)
        {
            <div class="col-md-12">
                <h4 class="text-center">Employees List</h4>
                <table class="table table-bordered table-striped dataTable">
                    <thead class="bg-dark text-white">
                        <tr>
                            <th>Employee Number</th>
                            <th>Employee Name</th>
                            <th>Role</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var emp in Model.employeeWithRoles.OrderBy(p => p.EmployeeName))
                        {
                            <tr>
                                <td>@emp.employeeID</td>
                                <td>@emp.EmployeeName</td>
                                <td>
                                    <span class="me-1">@emp.RoleName</span>
                                </td>
                                <td class="text-center">
                                    <div class="btn-group" role="group">
                                       @* <input type="hidden" name="UserId" value="@emp.Id" />*@
                                        <a asp-controller="TS" asp-action="ViewReport" asp-route-id="@emp.Id" class="btn btn-primary">
                                            <i class="bi bi-pencil-square"></i> View Report
                                        </a>
                                        <a asp-controller="TS" asp-action="AssignWork" asp-route-id="@emp.Id" class="btn btn-danger">
                                            <i class="bi bi-plus-circle"></i> Assign Work
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
    </div>
</div>



@section Scripts {
   

    <script>
        $(document).ready(function () {
            $('table.dataTable').DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
                "language": {
                    "paginate": {
                        "previous": "&laquo;",
                        "next": "&raquo;"
                    }
                }
            });
        });
     </script>
                }