Trac_WorkReport/Controllers/DesignationController.cs
using Microsoft.AspNetCore.Mvc;

using Trac_WorkReport.Models;
using WorkReport.DataAccess.Data;
using WorkRport.DataAccess.Repository.IRepository;

namespace Trac_WorkReport.Controllers
{
    public class DesignationController : Controller
    {
        private readonly  IDesignationRepository _designationRepo;
        public DesignationController(IDesignationRepository db)
        {
            _designationRepo = db;
        }

        public IActionResult Index()
        {
          List<Designation> objdesignation = _designationRepo.GetAll().ToList();
            return View(objdesignation);
        }

        public IActionResult Create() {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Designation obj)
        {
            _designationRepo.Add(obj);
            _designationRepo.save();
            return RedirectToAction("Index");
        }


        public IActionResult Edit(int? id)
        {
            if(id == null || id==0)
            {
                return NotFound();
            }
            Designation? designationfromDb = _designationRepo.Get(u=>u.DesId==id);
            //Designation? designationfromDb1 = _db.Designations.FirstOrDefault(u=>u.DesId == id);
            //Designation? designationfromDb2 = _db.Designations.Where(u => u.DesId == id).FirstOrDefault();
            if (designationfromDb == null)
            {
                return NotFound();
            }
            return View(designationfromDb);
        }

        [HttpPost]
        public IActionResult Edit(Designation obj)
        {
            if(ModelState.IsValid)
            {
                _designationRepo.update(obj);
                _designationRepo.save();
                return RedirectToAction("Index");

            }
            return View();
        }



        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Designation? designationfromDb = _designationRepo.Get(u=>u.DesId==id);
           // Designation? designationfromDb1 = _db.Designations.FirstOrDefault(u => u.DesId == id);
           // Designation? designationfromDb2 = _db.Designations.Where(u => u.DesId == id).FirstOrDefault();
            if (designationfromDb == null)
            {
                return NotFound();
            }
            return View(designationfromDb);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            Designation? obj = _designationRepo.Get(u => u.DesId == id); if (obj == null)
            {
                return NotFound();
            }
            _designationRepo.Remove(obj);
            _designationRepo.save();
            return RedirectToAction("Index");
           
            //return View();
        }
    }
}

Trac_WorkReport/Controllers/UserController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using Trac_WorkReport.Models;
using WorkReport.Models;

namespace Trac_WorkReport.Controllers
{
    public class UserController : Controller
    {
        private readonly Microsoft.AspNetCore.Identity.UserManager<ApplicationUser> _userManager;
        private readonly Microsoft.AspNetCore.Identity.RoleManager<ApplicationRole> _roleManager;

        public UserController(Microsoft.AspNetCore.Identity.UserManager<ApplicationUser> userManager, Microsoft.AspNetCore.Identity.RoleManager<ApplicationRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        // Display logged-in user details and all users
        public async Task<IActionResult> Index()
        {
            // Get the currently logged-in user
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null)
            {
                return NotFound();
            }

            // Fetch the roles of the logged-in user
            var currentUserRoles = await _userManager.GetRolesAsync(currentUser);
           
            var allUsers = await _userManager.Users.ToListAsync();
            var allUsersWithRoles = new List<EditUserViewModel>();
           
            //var model = new UserIndexViewModel
            //{
            //    CurrentUser = new EditUserViewModel
            //    {
            //        Id = currentUser.Id,
            //        Email = currentUser.Email,
            //        EmployeeName = currentUser.EmployeeName,
            //        Roles = currentUserRoles.Select(r => new RoleViewModel
            //        {
            //            RoleName = r,
            //            IsSelected = true
            //        }).ToList()
            //    },

            //};

            foreach (var user in allUsers)
            {
                var roles = await _userManager.GetRolesAsync(user);
                allUsersWithRoles.Add(new EditUserViewModel
                {
                    Id = user.Id,
                    Email = user.Email,
                    employeeID = user.EmployeeID,
                    EmployeeName = user.EmployeeName,
                    Roles = roles.Select(r => new RoleViewModel
                    {
                        RoleName = r,
                        IsSelected = true
                    }).ToList()
                });
            }

            var model = new UserIndexViewModel
            {
                CurrentUser = new EditUserViewModel
                {
                    Id = currentUser.Id,
                    Email = currentUser.Email,
                    EmployeeName = currentUser.EmployeeName,
                    Roles = currentUserRoles.Select(r => new RoleViewModel
                    {
                        RoleName = r,
                        IsSelected = true
                    }).ToList(),
                  
                },
                AllUsersWithRoles = allUsersWithRoles
            };

            return View(model);
        }


            // Display the form for editing a user
            public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            var userRoles = await _userManager.GetRolesAsync(user);
            var allRoles = await _roleManager.Roles.ToListAsync();

            var model = new EditUserViewModel
            {
                Id = user.Id,
                Email = user.Email,
                EmployeeName = user.EmployeeName,
                Roles = allRoles.Select(r => new RoleViewModel
                {
                    RoleName = r.Name,
                    IsSelected = userRoles.Contains(r.Name)
                }).ToList()
            };

            return View(model);
        }

        // Handle the form submission to edit a user
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await _userManager.FindByIdAsync(model.Id);
            if (user == null)
            {
                return NotFound();
            }

            user.Email = model.Email;
            user.UserName = model.Email;

            var result = await _userManager.UpdateAsync(user);
            if (!result.Succeeded)
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
                return View(model);
            }

            var userRoles = await _userManager.GetRolesAsync(user);
            var selectedRoles = model.Roles.Where(r => r.IsSelected).Select(r => r.RoleName);
            var rolesToAdd = selectedRoles.Except(userRoles);
            var rolesToRemove = userRoles.Except(selectedRoles);

            await _userManager.AddToRolesAsync(user, rolesToAdd);
            await _userManager.RemoveFromRolesAsync(user, rolesToRemove);

            return RedirectToAction("Index");
        }

        // Display the form for deleting a user
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // Handle the form submission to delete a user
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            var result = await _userManager.DeleteAsync(user);
            if (!result.Succeeded)
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
                return View(user);
            }

            return RedirectToAction("Index");
        }
    }

    // View model for editing user
    //public class EditUserViewModel
    //{
    //    public string Id { get; set; }
    //    public string Email { get; set; }
    //    public List<RoleViewModel> Roles { get; set; }
    //}

    //// View model for user roles
    //public class RoleViewModel
    //{
    //    public string RoleName { get; set; }
    //    public bool IsSelected { get; set; }
    //}


    // View model for the user index page
    public class UserIndexViewModel
    {
        public EditUserViewModel CurrentUser { get; set; }
        public List<ApplicationUser> AllUsers { get; set; }
        public List<EditUserViewModel> AllUsersWithRoles { get; set; }
    }

    // View model for editing user
    public class EditUserViewModel
    {
        public string Id { get; set; }
        public string Email { get; set; } 
        public string EmployeeName { get; set; }

        public string employeeID { get; set; }
        public List<RoleViewModel> Roles { get; set; }
      
    }

    // View model for user roles
    public class RoleViewModel
    {
        public string RoleName { get; set; }
        public bool IsSelected { get; set; }
    }

   
}

Trac_WorkReport/Views/User/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using Trac_WorkReport.Controllers
@model EditUserViewModel


@{
    ViewData["Title"] = "Edit User";
}

<h1>Edit User</h1>

<form asp-action="Edit">
    <div class="form-group">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <div>
        <label>Roles</label>
        @foreach (var role in Model.Roles)
        {
            <div class="form-check">
                <input type="checkbox" asp-for="@role.IsSelected" class="form-check-input" />
                <label class="form-check-label">@role.RoleName</label>
            </div>
        }
    </div>

    <button type="submit" class="btn btn-primary">Save</button>
</form>

Trac_WorkReport/Views/User/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using Trac_WorkReport.Controllers
@model UserIndexViewModel

@{
    ViewData["Title"] = "User List";
}

@*<h1>User List</h1>

<table class="table">
    <thead>
        <tr>
            <th>Email</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.Email</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@user.Id">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@user.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>*@

<div class="container">


    <div class="row pt-4" style="display:none">
        <div class="col-6">
            <div class="col-6">
        <label asp-for="CurrentUser.Email" class="col-form-label">Email</label>
       </div>
            <div class="col-6">
            <input type="text" readonly="" class="form-control-plaintext" id="staticEmail" asp-for="CurrentUser.Email">
        </div>
        </div>
        <div class="col-6">
            <label asp-for="CurrentUser.Email" class="col-form-label">Email</label>
            <div >
                <input type="text" readonly="" class="form-control-plaintext" id="staticEmail" asp-for="CurrentUser.Email">
            </div>
        </div>
         <div class="col-6">
        <label asp-for="CurrentUser.Email" class="col-form-label">Email</label>
        <div>
            <input type="text" readonly="" class="form-control-plaintext" id="staticEmail" asp-for="CurrentUser.Email">
        </div>
        </div>
        <div class="col-6">
            <label asp-for="CurrentUser.Email" class="col-sm-2 col-form-label">Email</label>
            <div >
                <input type="text" readonly="" class="form-control-plaintext" id="staticEmail" asp-for="CurrentUser.Email">
            </div>
        </div>
        <div class="col-6">
            <label asp-for="CurrentUser.Email" class="col-sm-2 col-form-label">Email</label>
            <div >
                <input type="text" readonly="" class="form-control-plaintext" id="staticEmail" asp-for="CurrentUser.Email">
            </div>
        </div>
    </div>
        

    <div class="row pt-4">
        <!-- Title and Add Button Section -->
        <div class="col-6">
            <h2 class="text-primary">Users</h2>
        </div>
      @*  <div class="col-6 text-end">
            <a asp-controller="user" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> Add Designation
            </a>
        </div>*@

    </div>

    <!-- Designations Table -->
    <table id="designationsTable" class="table table-bordered table-striped dataTable">
        <thead>
            <tr>
                <th>Employee ID</th>
                <th>User Name</th>
                <th>Designation</th>
                
                <th>Email</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model.AllUsersWithRoles.OrderBy(u => u.EmployeeName))
            {
                <tr>
                    <td>@obj.employeeID</td>
                    <td>@obj.EmployeeName</td>
                    <td>@string.Join(", ",obj.Roles.Select(r=>r.RoleName))</td>
                    <td>@obj.Email</td>
                    <td>
                        <div class="w-50 btn-group" role="group">
                            <a asp-controller="Designation" asp-action="Edit" asp-route-id="@obj.Id" class="mx-1">
                                <i class="bi bi-pencil-square"></i>
                            </a>
                            <a asp-controller="Designation" asp-action="Delete" asp-route-id="@obj.Id" class="mx-1">
                                <i class="bi bi-archive-fill"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
@section Scripts {
    <!-- Initialize DataTables -->
    <script>
        $(document).ready(function () {
            $('table.dataTable').DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
                "language": {
                    "paginate": {
                        "previous": "&laquo;",
                        "next": "&raquo;"
                    }
                }
            });
        });
    </script>
}